# Generated by Django 2.0.2 on 2018-12-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('isrc', models.CharField(blank=True, max_length=30, null=True)),
                ('duration', models.CharField(blank=True, max_length=256, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_songs', to='recordings.Artist', to_field='artist_name')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recording',
            unique_together={('artist', 'title', 'isrc', 'duration')},
        ),
    ]
